api/urls.py
from django.urls import path
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name="api"
router = DefaultRouter()

router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls




# urlpatterns = [
#     path("reviews/", BookReviewsAPIView.as_view(), name='review-list'),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name='review-detail')
# ]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, review_page


urlpatterns =[
    path('', landing_page, name='landing_page'),
    path('review/', review_page, name='review_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('author/', include('author.urls')),

    path('api-auth/', include('rest_framework.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name='users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_picture.jpg")

users/forms.py
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "password")

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "profile_picture")

users/views.py
from django.contrib.auth import login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.forms import UserCreateForm,UserUpdateForm

class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form" : create_form
        }
        return render(request, 'users/register.html', context)

    def post(self,request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, 'users/register.html', context)


        # create user account



class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, 'users/login.html', {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
             
            

            messages.success(request, "You have successfully logged in 🎉🤩")

            return redirect("books:list")
        else:
            return render(request, 'users/login.html', {"login_form": login_form})



class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out 🖐")
        return redirect("landing_page")





class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect("users:login")
        return render(request, 'users/profile.html', {"user" : request.user})


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, 'users/profile-edit.html', {"form" : user_update_form})

    
    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user, 
            data=request.POST,
            files=request.FILES    
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile 👌👍")        

            return redirect("users:profile")

        return render(request, "users/profile-edit.html", {"form" : user_update_form})    

users/templates/users/login.html
{%extends "base.html" %}
{% load crispy_forms_tags %}

{%block title %}Our Login Page{% endblock %}


{% block content %}
{% comment %} 
    <h3>Login </h3> 

    <div class="row">
        <div class="col-5">
            <form method="post">
                {% csrf_token %}
    
                {{ login_form | crispy }}
    
                <button type="submit" class="btn btn-outline-secondary">Log in</button> <span class="ms-3">If you have not an account! You <a href="{% url 'users:register' %}">must register</a></span>
            </form>
        </div>
    </div> 

 {% endcomment %}


        <section class="vh-100 bg-image"
            style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDgRehsB2ucWfjtDUXMk-DMNdX6mtNmYk5Mw&usqp=CAU'); background-size:cover;">
            <div class="mask d-flex align-items-center h-100 ">
                <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div style="border-radius: 15px;">
                        <div class="card-body p-5">
                        <h4 class="text-center mb-4">Login</h4>

                        <form method="post">
                            {% csrf_token %}
            
                            {{ login_form | crispy }} 

                            <div class="d-flex justify-content-center">
                            <button type="submit"
                                class="btn btn-dark btn-lg mt-3">Sign in</button>
                            </div>

                            <p class="text-center mt-3 mb-0"> Don't have an account? <a href="{% url 'users:register' %}"
                                class="fw-bolder text-body"><u>Register here</u></a></p>

                        </form>

                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </section>



{% endblock %}

users/templates/users/profile-edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block title%} Profile Edit {%endblock%}

{%block content%}
    {% comment %} <h3>Edit Profile </h3>

    <div class="row">
        <div class="col-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
        
                {{ form | crispy }}
        
                <button type="submit" class="btn btn-outline-dark">Save</button>   
            </form>
        </div>
    </div> {% endcomment %}

    <section class="vh-100 bg-image"
        style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1OWEN4QwBi-R2xIhz-LBc4E9MuaQYSbwQ3BOenAvqgKZeqQB-Ktt_ZVkbq0iIoJBKJUw&usqp=CAU'); background-size:cover;">
        <div class="d-flex align-items-center h-100 ">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <h5 class="text-center mb-4">Profile edit</h5>

                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                        
                                    {{ form | crispy }} 

                                    <div class="d-flex justify-content-center">
                                    <button type="submit"
                                        class="btn btn-dark btn-lg mt-3">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    
{%endblock%}

users/templates/users/profile.html
{% extends "base.html" %}
 
{% block title %} Profile Page {% endblock %}

{% block content %}


    <div class="profile-page image d-flex flex-column justify-content-center align-items-center"> 
        <button class="btn btn-outline-dark">
            <img class="profile-pic" alt="Profile picture" src="{{ user.profile_picture.url }}">
        </button> 
        {% if user.first_name or user.last_name %}
            <span class="name mt-3"><b>Name:</b> {{user.first_name}} {{user.last_name}}</span> 
        {% endif %}
        <span class="idd my-2"><b>Username:</b> @{{user.username}}</span> 
        <span class="idd"><b>Email:</b> {{user.email}}</span> 
        <div class=" d-flex mt-3"> <a class="btn btn-dark edit-profile" href="{% url "users:profile-edit" %}">Edit profile</a> </div> 
        <div class=" px-2 rounded mt-4 date "> <span class="join">Joined <b>{{user.date_joined | date:"M d, Y"}}</b></span> </div>
    </div> 


    {% comment %} <h3> Profile Page</h3>

    

    <p>Username : {{user.username}}</p>
    <p>First name : {{user.first_name}}</p>
    <p>Last name : {{user.last_name}}</p>
    <p>Email : {{user.email}}</p>

    <span></span> {% endcomment %}

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Register Page {% endblock %}

{% block content %}

        
        <section class="vh-100 bg-image"
            style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi6MOoV-zrTZSaC6yonSoT7GqjVaPws9c1Ag&usqp=CAU'); background-size:cover;">
            <div class="mask d-flex align-items-center h-100 ">
                <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div style="border-radius: 15px;">
                        <div class="card-body p-4">
                        <h4 class="text-center mb-4">Create an account</h4>

                        <form method="post" action="{% url 'users:register' %}">
                            {% csrf_token %}
            
                            {{ form | crispy }} 

                            <div class="d-flex justify-content-center">
                            <button type="submit"
                                class="btn btn-outline-dark btn-lg mt-3">Register</button>
                            </div>

                            <p class="text-center text-muted mt-3 mb-0">Have already an account? <a href="{% url 'users:login' %}"
                                class="fw-bolder text-body"><u>Login here</u></a></p>

                        </form>

                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </section>

{% endblock %}