api/urls.py
from django.urls import path
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name="api"
router = DefaultRouter()

router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls




# urlpatterns = [
#     path("reviews/", BookReviewsAPIView.as_view(), name='review-list'),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name='review-detail')
# ]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView


app_name="books"

urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete-review")
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, review_page


urlpatterns =[
    path('', landing_page, name='landing_page'),
    path('review/', review_page, name='review_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('author/', include('author.urls')),

    path('api-auth/', include('rest_framework.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name='users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')

]

templates/base.html
{% load static %}
{% url 'books:list' as books_page_url %}
{% url 'review_page'  as review_page_url %}
{% url 'users:profile'  as profile_page_url %}
{% url 'users:profile-edit' as edit_profile_page_url %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Goodreads {% endblock %}</title>

        <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

</head>
<body class="mx-4">

    <nav class="navbar navbar-expand-lg mb-4 py-3" style="background-color: rgb(11, 130, 228);">
        <div class="container-fluid container-two ms-3">
          <a class="navbar-brand mx-3" href="{% url 'landing_page' %}">Goodreads </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == books_page_url %} active {% endif %} " aria-current="page" href="{{ books_page_url }}">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == review_page_url %} active {% endif %} " aria-current="page" href="{{ review_page_url }}">Reviews</a>
                </li>
            </ul> 
            <div>
                {% comment %} <p>
                    
                </p> {% endcomment %}
            </div>
            <div class="me-5">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle login-profile {% if request.path == profile_page_url or request.path == edit_profile_page_url %} active {% endif %} " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{request.user.username}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{ profile_page_url }}"><i class="bi bi-person-fill"></i>  Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}"><i class="bi bi-box-arrow-left"></i>  Logout</a></li>
                            </ul>
                        </li> 
                    </ul>
                {% else %}
                    <a class="btn btn-outline-dark" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
    </nav>


    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    
        {% block content %} {% endblock %}
    </div>


    

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</head>

templates/landing.html
{% extends "base.html" %}

{% block content %}
    {% comment %} <span class="mb-4">Goodreads</span> {% endcomment %}
    
    <h1 class="jt --debug ">
        <span class="jt__row">
          <span class="jt__text">Goodreads</span>
        </span>
        <span class="jt__row jt__row--sibling" aria-hidden="true">
          <span class="jt__text">Goodreads</span>
        </span>
        <span class="jt__row jt__row--sibling" aria-hidden="true">
          <span class="jt__text">Goodreads</span>
        </span>
        <span class="jt__row jt__row--sibling" aria-hidden="true">
          <span class="jt__text">Goodreads</span>
        </span>
    </h1>

    <div class="library mb-4 rounded">
        <div class="col-6 ms-5">
            <p class="col-9  p-5" style="color: #fff; "> <b>Goodreads</b> is the world`s largest site for readers and book recommendations.
                Our mission is to help people find and share books they love. Goodreads launched in January 2007.</p>

            <h5 class="col-9 ms-5" style="color: #fff; ">Book discovery</h5>
            <p class="col-9 ms-5" style="color: #fff; ">On the Goodreads website, users can add books to their personal bookshelves, rate and review books, see what their friends and authors are reading, 
                participate in discussion boards and groups on a variety of topics, and get suggestions for future reading choices based on their reviews of previously read books</p>
            
        </div>
    </div>



    <footer class="me-auto" style="background-color: rgb(11, 130, 228); width:1300px">     
        <div class="text-center p-2 " style="background-color: rgba(0, 0, 0, 0.2);">
            <div>
                <a href="https://github.com/Asadbek-Web"><img  class="mx-1 footer-icon" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTut0MEnAzgz3ejcE4eWIXHwQbafdMTOr5Fo2JwWH3zlyBF6j4ozmXdsaSdt73hZli4R0Y&usqp=CAU"></a>
                <a href="https://t.me/Abdumalikov_A_Z"><img  class="mx-1 footer-icon" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPPn2ndg3PnycZSczVsg0zIoFx9rnDJ9btfw&usqp=CAU"></i></a>
                <a href="mailto:asadbekabdumalikovfifth@gmail.com"><img class="mx-1 footer-icon" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT4tNXUcGpAX_ywFok1ADMfGGX6_NVdcg6qA&usqp=CAU"></a>
            
            </div>

            <p class="mt-1 mb-1">Asadbek_Abdumalikov &trade; | 2022</p>
        </div>
    </footer>
    

{% endblock %}

templates/review.html
{% extends "base.html" %}

{% block title %} Review Page {% endblock %}


{% block content %} 
    <h3 class="ms-3 headings">All reviews</h3>

    {% for review in page_obj %}

        <div class="container posts-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4 list-page">
                        <div class="card-body" >
                            <div class="media mb-3">
                                <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                                <div class="media-body ml-3">
                                    <b class="badge bg-secondary text-wrap fs-6 my-1" style="width: auto; height:auto;">{{ review.user.username }}</b>
                                        evaluated <b>{{ review.stars_given }}</b> stars for this book | <span class="fw-lighter">{{ review.created_at | date:"M d Y" }}</span>
                                </div>
                            </div>
                            <p class="fw-lighter"style="font-size: 14px;">
                                {{ review.comment | truncatechars:250 }}
                            </p>
                            <img class="cover-pic rounded" alt="Cover image" src="{{ review.book.cover_picture.url }}">
                        </div>
                        <span class="mb-3">
                            <a href="{% url 'books:detail' review.book.id %}" class="link-red ms-3 sea-more">More info &#10132;</a> 
                        </span>
                    </div>
                </div>
            </div>
        </div>
    
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>

{% endblock %}