api/urls.py
from django.urls import path
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name="api"
router = DefaultRouter()

router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls




# urlpatterns = [
#     path("reviews/", BookReviewsAPIView.as_view(), name='review-list'),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name='review-detail')
# ]

author/urls.py
from django.urls import path
from author.views import BookAuthorView

app_name = "author"

urlpatterns = [
    
    path('<int:id>/', BookAuthorView.as_view(), name="author")
]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView


app_name="books"

urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete-review")
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, review_page


urlpatterns =[
    path('', landing_page, name='landing_page'),
    path('review/', review_page, name='review_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('author/', include('author.urls')),

    path('api-auth/', include('rest_framework.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone


from users.models import CustomUser

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")

    def __str__(self):      
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    # author_picture = models.ImageField(default="default_cover.jpg")


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"



class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators = [ MinValueValidator(1), MaxValueValidator(5) ]
    )
    created_at = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

books/forms.py
from django import forms

from books.models import BookReview

class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('comment', 'stars_given')

books/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from books.forms import BookReviewForm
from django.urls import reverse
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin

from books.models import Book, BookReview


# class BooksView(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all()
#     context_object_name = "books" 
#     paginate_by = 2

class BooksView(View):
    def get(self, request): 
        books = Book.objects.all().order_by('id')
        search_query= request.GET.get('q', '')
        if search_query :
            books = books.filter(title__icontains=search_query)


        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        return render(request, "books/list.html", {"page_obj": page_obj, "search_query": search_query})


# class BookDetailView(DetailView):
#     template_name = "books/detail.html"
#     pk_url_kwarg = "id"
#     model = Book

class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )

            return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})



class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)

        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_form": review_form})


    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"id": book.id}))


        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_form": review_form})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request,  book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        return render(request, "books/confirm_delete_review.html", {"book": book, "review": review})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request,  book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
       
        review.delete()
        messages.success(request, "You have successfully removed this review 👌")

        return redirect(reverse("books:detail", kwargs={"id": book.id}))

books/templates/books/confirm_delete_review.html
{% extends "base.html" %}

{% block title %} Delete review {% endblock %}

{% block content %}

    <h3 class="mb-5">Are you sure that you want to delete this review?</h3>
    <div>
        <p class="font-monospace">
            <b class="fs-5">Book: </b> {{ book.title }}
        </p> <hr>
        <p class="font-monospace">
            <b class="fs-5">Comment: </b>{{ review.comment }}
        </p>
        <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-danger">Yes</a> 
        <a href="{% url 'books:detail' book.id %}" class="btn btn-outline-dark">No</a>
    </div>

{% endblock %}

books/templates/books/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %} Book Detail Page {% endblock %}


{% block content %}
    <h3>Book Details</h3>

    <div class="row mb-5">
        <div class="col-2">
            <img class="cover-pic rounded" alt="cover image" src="{{ book.cover_picture.url }}">   
        </div>

        <div class="col-6 ms-4">
            <h3>{{ book.title }}</h3>

            {% comment %} {% if book_author.is_valid %} {% endcomment %}
                <span class="fw-lighter">
                    Written by <a href={% url 'author:author' book.id %}>
                    {% for book_author in book.bookauthor_set.all %}
                        {% if forloop.last %}
                            {{ book_author.author.full_name }}
                        {% else %}
                            {{ book_author.author.full_name }},
                        {% endif %}
                    {% endfor %} </a>
                </span>
            {% comment %} {% else %} {% endcomment %}

                <p> {{ book.description }} </p>
                <p class="fst-italic text-muted"><b>ISBN:</b>( {{ book.isbn }} ) </p>
            {% comment %} {% endif %} {% endcomment %}
        </div>
    </div>

    <div class="row mb-5">
        <div class="col-5">

            <form method="post" action="{% url 'books:reviews' book.id %}"> 
                {% csrf_token %}

                {{ review_form | crispy }}

                <button class="btn btn-primary my-3">Save review</button>
            </form>
            {% comment %} <input type="hidden" name="next" value="{{ request.path }}">
            <button type="submit">&#10094;Go back</button> {% endcomment %}
            <a href="{% url 'books:list' %}" class="back">&#10094; Go back</a>
        </div>
    </div>


    {% if book.bookreview_set.exists %}
        <h3>Reviews</h3> <hr>

        {% for review in book.bookreview_set.all %}

            <div class="row mb-3">
                <div class="col-1">
                    <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}">
                </div>

                <div class="col-7 ms-3">
                    <div class="mb-3">
                        <b class="badge bg-dark text-wrap fs-6" style="width: auto; height:auto;">{{ review.user.username}}</b> 
                        rated it <b>{{ review.stars_given }}</b> stars |  <span class="font-monospace">{{ review.created_at }}⌚ </span> 
                        {% if review.user == request.user %}
                            | 
                            <a href="{% url 'books:edit-review' book.id review.id %}"> <i class="bi bi-pen link-dark"></i></a>
                            <a href="{% url 'books:confirm-delete-review' book.id review.id %}"> <i class="bi bi-trash3-fill link-danger"></i></a>
                        {% endif %}
                        </div>
                    <p class="fw-lighter" style="font-size: 14px;">{{ review.comment }}</p>
                </div>
            </div>

        {% endfor %}
    {% endif %}
 
{% endblock %}

books/templates/books/edit_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit review page {% endblock %}

{% block content %}
    <h3>Edit review 📝</h3>

    <div class="row mb-5">
        <div class="col-5">
            <form method="post" action="{% url 'books:edit-review' book.id  review.id %}"> 
                {% csrf_token %}

                {{ review_form | crispy }}

                <button class="btn btn-primary">Save changes</button>
            </form>
        </div>
    </div>

{% endblock %}

books/templates/books/list.html
{% extends "base.html"%}


{% block title%} Books Page {% endblock %}

{% block content %}

    <h1>Books </h1>

    <div class="row mb-3">
        <div class="col-4">
            <form class="d-flex" method="get">
                <input class="form-control me-2" placeholder="🔎 Search" type="text" name="q" value="{{ search_query }}">

                <button class="btn btn-outline-primary">Search</button>
            </form>
        </div>
    </div>

    {% if page_obj %}
        {% for book in page_obj.object_list %}
            <div class="row mb-4 ms-1 list-page">
                <div class="col-2">
                    <img class="cover-pic rounded" alt="Cover image" src="{{ book.cover_picture.url }}">
                </div>
                <div class="col-6 ms-4">
                    <h5>{{ book.title }}</h5>
                    <p>{{ book.description | truncatechars:600 }}</p>

                    <span><a class="sea-more" href="{% url 'books:detail' book.id %}">Sea more➩</a></span>
                </div>
            </div>
        {% endfor %}
        
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>

    {% else %}
        No books found😢<br>

        <a class="back" href="{% url 'books:list' %}"> Back </a>
    {% endif %}
    

{% endblock %}